export const HOME = '/'
export const COURSES = '/courses/'
export const DASHBOARD = '/dashboard/'
export const VERIFY_EMAIL = '/verify-email/'
export const TEACHER_COURSE = '/dashboard/teacher-courses/'
export const TESTS = '/tests/'